# Generated by Django 4.2.3 on 2024-03-12 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('colcod', models.AutoField(db_column='ColCod', primary_key=True, serialize=False)),
                ('colnom', models.CharField(db_column='ColNom', max_length=40)),
                ('colape', models.CharField(db_column='ColApe', max_length=40)),
                ('colfecnac', models.DateField(db_column='ColFecNac')),
                ('colpos', models.CharField(db_column='ColPos', max_length=40)),
            ],
            options={
                'db_table': 'colaborador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('horcod', models.AutoField(db_column='HorCod', primary_key=True, serialize=False)),
                ('hordia', models.CharField(db_column='HorDia', max_length=9)),
                ('horini', models.TimeField(db_column='HorIni')),
                ('horfin', models.TimeField(db_column='HorFin')),
                ('horcolcod', models.ManyToManyField(db_column='HorColCod', to='Gestion.colaborador')),
            ],
            options={
                'db_table': 'horario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('contrcod', models.AutoField(db_column='ContrCod', primary_key=True, serialize=False)),
                ('contrfecini', models.DateField(db_column='ContrFecIni')),
                ('contrfecfin', models.DateField(blank=True, db_column='ContrFecFin', null=True)),
                ('contreps', models.CharField(db_column='ContrEps', max_length=100)),
                ('contrseg', models.CharField(db_column='ContrSeg', max_length=100)),
                ('contrcolcod', models.ForeignKey(db_column='ContrColCod', on_delete=django.db.models.deletion.CASCADE, to='Gestion.colaborador')),
            ],
            options={
                'db_table': 'contrato',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('concod', models.AutoField(db_column='ConCod', primary_key=True, serialize=False)),
                ('contip', models.CharField(db_column='ConTip', max_length=40)),
                ('coninf', models.CharField(db_column='ConInf', max_length=40)),
                ('concolcod', models.ForeignKey(db_column='ConColCod', on_delete=django.db.models.deletion.CASCADE, to='Gestion.colaborador')),
            ],
            options={
                'db_table': 'contacto',
                'managed': True,
            },
        ),
    ]
